<?php
/*******************************************************************
/ ProArcadeScript
/ File description:
/ commenting system configuration
/ WARNING! This file is autogenerated. Please backup before 
/ manual editing
/
/*******************************************************************/
$cC = array (
	"contentpermit"	=>	2,
	"contentpremod"	=>	2,
	"sitepermit"	=>	2,
	"sitepremod"	=>	0,
	"filters"		=>	1,
	"ban"			=>	1,
	"instantdelete"	=>	1,
	"sendcopy"		=>	1,
	"mindelay"		=>	5	// seconds; the minimum time interval between page load and first permissible comment
);
return;
?>

