<?php
/*******************************************************************
/ ProArcadeScript 
/ File description:
/ Messages mostly
/
/*******************************************************************/

// Messages, helper strings
$cLang = array(
	"sActivationSubj"	=>	"Welcome to !SITENAME!!",
	"sGuest"			=>	"Guest",
	"sAdmin"			=>	"Admin",
	"sHome"				=>	"Home",
	"msgFeatured"		=>	"Featured Game",
	"msgNoNews"			=>	"There are no news yet",
	"msgMore"			=>	"Read more",
	"msgNoFavorites"	=>	"You have no favorite games yet. To add one, open any game you like and click the 'Add to favorites' link.",
	"msgLogin"			=>	"Log in to manage your site",
	"msgAccountCreated"	=>	"Your account has been created. However, this site requires account activation. An activation key has been sent to the e-mail address you provided. Please check your e-mail for further information.",
	"errActivate"		=>	"Something went wrong with your account's activation. Please make sure you entered the correct activation URL.",
	"msgActivateSuccess"=>	"Congratulations! Your account has been activated. You may now log in using your email and password to use all cool features of our site.",
	"msgActivated"		=>	"Your account is allready active.",
	"msgLoggedIn"		=>	"Welcome back !NAME!!<br/>",
	"msgNotActive"		=>	"!NAME!, your accout is not active yet.<br/> You will find the instructions about its activation in the email we have sent to you. Please check your inbox.",
	"msgPrivateFeedback"=>	"Private feedback message from !URL!",
	"msgFeedback"		=>	"Site feedback at !URL!",
	"msgPrivateComment"	=>	"Private game comment from !URL!",
	"msgComment"		=>	"Game comment at !URL!",
	"msgNothingFound"	=>	"We did not find any results for !QUERY!",
	"errNoGame"			=>	"Sorry, but the game you are trying to acceess does not exist in our database or temporary disabled. Please contact our user support department if you need any additional information.",
	"errEmptyCat"		=>	"Sorry, but there are no games in this category yet",
	"msgAGameAdded"		=>	"The game is successfully added.",
	"msgADeleteGame"	=>	"Are you sure you want to completely delete the selected game?",
	"msgADeleteBlock"	=>	"Are you sure you want to completely delete the selected page block? Please note, this operation can't be undone.",
	"msgADeletePage"	=>	"Are you sure you want to completely delete the selected page? Please note, this operation can't be undone.",
	"msgADeleteComment"	=>	"Are you sure you want to delete this comment?",
	"msgANoDataForPeriod"	=>	"There are no records in the database for this period",
	"errAEmpty"			=>	"Can't be empty!",
	"errAPassword"		=>	"The passwords you entered do not match. Please reenter",
	"errALogin"			=>	"Wrong login or password. Please reenter.",
	"errAWrongFormat"	=>	"Unsupported file format",
	"errAUpload"		=>	"Error! Can't upload a file. Please check the content folders' attributes. ",
	"errAFileWrite"	=>	"Error! Can't write to the file. Please check its attrubutes and attributes of the parent folder.",
	"errAPageExists"	=>	"Error! This page allready exists. Please enter another ID.",
	// Added in v1.3
	'msgADeleteUsert'	=>	'Are you sure you want to delete this user along with the information about his/her favorites and friends?',
   'errAFolderAccess'=> 'Error! Can\'t access folder ',
   'msgABulkEmpty'	=>	'The "/content/bulkadd/" folder is empty or description files have incorrect structure or some media files are missing.',
   'msgABulkResult'	=>	'All done. !GAMES! games has been added.',
   'errAMove'			=>	'Error! Can\'t move the file: ',
   'sLanding'        => 'Play more free games at !SITENAME!.',
	'sUserHome'       => 'My Profile',
	'sUserFavorites'  => 'Favorites',
	'sUserSubmit'     => 'Submit game',
	'sUserList'       => 'Users',
	'sUserMail'       => 'Mail',
	'sUserSettings'   => 'Settings',
	'sUserLogout'   	=> 'Logout',
	'sUserPath'       => '\'s profile',
	'sRegistration'   => 'New user registration',
	'sActivation'     => 'User activation',
	'sLogin'          => 'User login',
	'sUser'           => 'User',
	'sex1'		      => 'Male',
	'sex2'      		=> 'Female',
	'sex0'   			=> 'Alien',
	'na'    			   => 'N/A',
	'sNoLocation'     => 'nowhere',
	'status0'         => 'Novice',
	'status1'         => 'Active',
	'status2'         => 'Veteran',
	'status3'         => 'Hero',
	'status4'         => 'Star',
	'status5'         => 'Superstar',
	'msgDone'         => 'All done!',
	'msgChangesSaved'	=> 'Changes saved!',
	'msgNewEmailNote'	=> 'Please note: you should confirm your new email address before next login. See details in the message which has just been sent to the new email address.',
	'msgEmailConfirmed'  => 'Done. The email address is confirmed',
	'msgPasswordSent' => 'The new password is sent to your email.',
	'msgUnconfirmed'  => 'Your account is not activated yet. Please check your inbox, there must be a message containing the instructions about its activation.',
	'msgNoData'       => 'No data',
	'msgNoFriends'    => 'There are no friends yet',
	'msgNoFans' 	   => 'Sorry, you have no fans yet',
	'msgNoUser'       => 'User not found',
	'msgVoteThanks'	=>	'Thank you, your vote is saved',
	'sNewMailSubj'    => 'Please confirm new email address',
	'sNewPassSubj'    => 'New password',
	'errVoteCheat'		=>	'Sorry, but you can\'t vote for this game any more.',
	'errUnauthorised'	=>	'This page is for registered users only. Please register',
	'errNewUsername'  => 'Unacceptable username.',
	'errUserExists'   => 'Entered username is already in use. Please try another.',
	'errPassword'  	=> 'Unacceptable password.',
	'errValue'			=> 'Error! Unacceptable value.',
	'errNoUser'       => 'Our records do not contain a user with specified username/email. Please check the details you\'ve entered and try again.',
	'errEmail'        => 'Wrong address format. Please correct and try again.',
	'errEmailExists'  => 'Entered email address is associated with another user\'s account. Please use another one.',
	'errSendEmail'    => 'Sorry, but the system can\'t send you the message. Please contact site admin.',
	'errNoNewEmail'   => 'Error! The new address is already activated or there is an error in the confirmation link. Please check it',
	'errEmailBusy'    => 'Sorry, this email address is used by another user',
	'errLargeFile'    => 'Error! The file is too large.',
	'errDimensions'   => 'Error! Dimensions do not meet the requirements',
	'errUpload'       => 'Error! Can\'t upload this',
	'errUnknown'      => 'Error! Something went wrong...',
	'errBadRequest'   => 'Error! The parameters in your query do no match our requirements... a hack attempt?',
	'errNoUser'       => 'Error! User not found.',
	'errAFile'        => 'Error! You should either upload a file or enter a path to it.'
);

// For arcade frontend
$cSortStr = array( 
	'rand'			=>	'Random',
	'date'			=>	'Most Recent', 
	'title'			=>	'All', 
	'plays_total'	=>	'Most Popular', 
	'plays_today'	=>	'Today\'s Hot',
	'rating'		=>	'Top Rated'
);

// For admin panel.
$cSortTitle = array( 	
	'rand'			=>	'Random',
	'date'			=>	'By date added', 
	'title'			=>	'By title', 
	'plays_total'	=>	'By total number of plays', 
	'plays_today'	=>	'By number of plays today',
	'rating'		=>	'By rating'
);
?>