<?php
/*******************************************************************
/ ProArcadeScript 
/ File description:
/ additional pages configuration file.
/ WARNING! This file is autogenerated. Please do not edit manually
/
/*******************************************************************/
$cP = array (
	"about.html" => array( "title"=>"About", "description"=>"About site", "keywords"=>"about, flash, games, site", "active"=>1, "menutitle"=>"About", "mainmenu"=>1, "footermenu"=>1, "comments"=>"Site description" ),
	"terms.html" => array( "title"=>"Terms of Use", "description"=>"terms of use", "keywords"=>"terms of use", "active"=>0, "menutitle"=>"Terms of Use", "mainmenu"=>0, "footermenu"=>1, "comments"=>"" ),
);

return;
?>
