<?php
/*******************************************************************
/ ProArcadeScript 
/ File description:
/ commenting system configuration
/ WARNING! This file is autogenerated. Please backup before 
/ manual editing
/
/*******************************************************************/
$cC = array (
	"contentpermit"	=>	!CONTENT!,
	"contentpremod"	=>	!CONTENTPREMOD!,
	"sitepermit"	=>	!SITE!,
	"sitepremod"	=>	!SITEPREMOD!,
	"filters"		=>	!FILTERS!,
	"ban"			=>	!BAN!,
	"instantdelete"	=>	!DELETE!,
	"sendcopy"		=>	!SENDCOPY!,
	"mindelay"		=>	!DELAY!	// seconds; the minimum time interval between page load and first permissible comment
);
return;
?>

