<?php
/*******************************************************************
/ ProArcadeScript
/ File description:
/ additional pages configuration file.
/ WARNING! This file is autogenerated. Please do not edit manually
/
/*******************************************************************/
$cP = array (
<!-- BEGIN DYNAMIC BLOCK: dynList -->	
	"!ID!" => array( "title"=>"!TITLE!", "description"=>"!DESCRIPTION!", "keywords"=>"!KEYWORDS!", "active"=>!ACTIVE!, "menutitle"=>"!MENUTITLE!", "mainmenu"=>!MAINMENU!, "footermenu"=>!FOOTERMENU!, "comments"=>"!COMMENTS!" ),
<!-- END DYNAMIC BLOCK: dynList -->
);

return;
?>